sudo: false
cache: bundler
language: ruby
rvm:
  - 2.3.1
  - 2.4.2
before_install:
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do gem install bundler -v 1.15.4
after_script: bundle exec codeclimate-test-reporter
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/32a0b937854e89d6ae58
    on_success: change
    on_failure: always
    on_start: never
